### ISSUE TITLE
Potential Violation Detected

### ISSUE THREAD

**Issue by assignguard-support** [prathik-k/CSE-6242-DVA#1]
Hey prathik-k!

This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.

At your earliest convenience, please do one of the following:
  - disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
  - remove any content could be in violation of copyright law
  - remove any content could be in violation of an institution's academic integrity policy

Please feel free to continue any discussion here. Thanks!

**Comment by assignguard-support** [comment]
:wave: gentle reminder!

**Comment by prathik-k** [comment]
Hi,
Thanks for raising this issue. Please reply in a comment with which sections constitute copyright infringement, and I shall take action accordingly. I will be closing this issue on Nov. 27th if I do not receive a response by then.

**Comment by prathik-k** [comment]
Closed since no response was received.
